name: Auto Deploy after push

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Build, Deploy to S3 bucket
    runs-on: [ubuntu-latest]

    strategy:
      matrix:
        node-version: [14.15.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Npm install
        run: npm install

      - name: Build
        run: npm run build

      - name: Transfer to S3 for serving static
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: chamchipack
          AWS_ACCESS_KEY_ID: AKIAX4AGL7THU5M3KBV2
          AWS_SECRET_ACCESS_KEY: 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
          AWS_REGION: SEOUL
          SOURCE_DIR: "dist"